"""Added question ID to Answers table.  Not a FK.

Revision ID: 52097977a0b0
Revises: b2fb0637c645
Create Date: 2024-11-29 20:13:22.963578

"""
from alembic import op
import sqlalchemy as sa
import programming_quiz_web_app


# revision identifiers, used by Alembic.
revision = '52097977a0b0'
down_revision = 'b2fb0637c645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Answers', schema=None) as batch_op:
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
