"""Initial database version.

Revision ID: 63e55cc6f3f7
Revises: 
Create Date: 2024-10-17 19:57:39.059656

"""
from alembic import op
import sqlalchemy as sa
import programming_quiz_web_app
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63e55cc6f3f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('given_name', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('Applicants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Applicants_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_Applicants_surname'), ['surname'], unique=False)

    op.create_table('Permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('Permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Permissions_name'), ['name'], unique=True)

    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('given_name', sa.String(length=100), nullable=False),
    sa.Column('account_state', sa.String(length=45), nullable=False),
    sa.Column('account_created', programming_quiz_web_app.models.TZDateTime(), nullable=False),
    sa.Column('last_login', programming_quiz_web_app.models.TZDateTime(), nullable=True),
    sa.Column('token', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_account_state'), ['account_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_Users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_Users_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_Users_surname'), ['surname'], unique=False)

    op.create_table('Quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('default_time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('time_created', programming_quiz_web_app.models.TZDateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['Users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('Quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Quizzes_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_Quizzes_time_created'), ['time_created'], unique=False)

    op.create_table('UsersPermissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['Permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('Assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('expiry', programming_quiz_web_app.models.TZDateTime(), nullable=False),
    sa.Column('start_time', programming_quiz_web_app.models.TZDateTime(), nullable=True),
    sa.Column('submit_time', programming_quiz_web_app.models.TZDateTime(), nullable=True),
    sa.Column('score', sa.Double(), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('url_pin', sa.String(length=10), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['Users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quiz_id'], ['Quizzes.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('ChoiceQuestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=45), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('auto_grade', sa.Boolean(), nullable=False),
    sa.Column('possible_points', sa.Double(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['Quizzes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('ChoiceQuestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ChoiceQuestions_order'), ['order'], unique=False)

    op.create_table('FreeResponseQuestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('solution', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('possible_points', sa.Double(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['Quizzes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('FreeResponseQuestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_FreeResponseQuestions_order'), ['order'], unique=False)

    op.create_table('Answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=45), nullable=False),
    sa.Column('question_title', sa.String(length=300), nullable=False),
    sa.Column('question', mysql.LONGTEXT(), nullable=False),
    sa.Column('question_solution', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('answer', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('possible_points', sa.Double(), nullable=False),
    sa.Column('awarded_points', sa.Double(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['Assignments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ApplicantsAssignments',
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['Applicants.id'], ),
    sa.ForeignKeyConstraint(['assignment_id'], ['Assignments.id'], ),
    sa.PrimaryKeyConstraint('applicant_id', 'assignment_id')
    )
    op.create_table('Options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_text', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('option_weight', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['ChoiceQuestions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('Options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Options_order'), ['order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Options_order'))

    op.drop_table('Options')
    op.drop_table('ApplicantsAssignments')
    op.drop_table('Answers')
    with op.batch_alter_table('FreeResponseQuestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_FreeResponseQuestions_order'))

    op.drop_table('FreeResponseQuestions')
    with op.batch_alter_table('ChoiceQuestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ChoiceQuestions_order'))

    op.drop_table('ChoiceQuestions')
    op.drop_table('Assignments')
    op.drop_table('UsersPermissions')
    with op.batch_alter_table('Quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Quizzes_time_created'))
        batch_op.drop_index(batch_op.f('ix_Quizzes_name'))

    op.drop_table('Quizzes')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_surname'))
        batch_op.drop_index(batch_op.f('ix_Users_id'))
        batch_op.drop_index(batch_op.f('ix_Users_email'))
        batch_op.drop_index(batch_op.f('ix_Users_account_state'))

    op.drop_table('Users')
    with op.batch_alter_table('Permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Permissions_name'))

    op.drop_table('Permissions')
    with op.batch_alter_table('Applicants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Applicants_surname'))
        batch_op.drop_index(batch_op.f('ix_Applicants_email'))

    op.drop_table('Applicants')
    # ### end Alembic commands ###
