"""Changed applicant and assignments to 1:n relationship.

Revision ID: b2fb0637c645
Revises: 63e55cc6f3f7
Create Date: 2024-11-29 00:55:22.209863

"""
from alembic import op
import sqlalchemy as sa
import programming_quiz_web_app
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2fb0637c645'
down_revision = '63e55cc6f3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ApplicantsAssignments')
    with op.batch_alter_table('Assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Applicants', ['applicant_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('applicant_id')

    op.create_table('ApplicantsAssignments',
    sa.Column('applicant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('assignment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['Applicants.id'], name='ApplicantsAssignments_ibfk_1'),
    sa.ForeignKeyConstraint(['assignment_id'], ['Assignments.id'], name='ApplicantsAssignments_ibfk_2'),
    sa.PrimaryKeyConstraint('applicant_id', 'assignment_id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
